version: "3"
services:
  claon_database:
    container_name: claon_admin_db
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "claon_db"
      POSTGRES_USER: "claon_user"
      POSTGRES_PASSWORD: "claon_password"
  redis:
    image: redis:6.0.5
    container_name: claon_admin_redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
  rabbit_mq:
    image: rabbitmq:3.11.16
    container_name: claon_admin_rabbit_mq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "CLAON-RABBITMQ-COOKIE"
      RABBITMQ_DEFAULT_USER: "claon_user"
      RABBITMQ_DEFAULT_PASS: "claon_password"
